services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_DB=ecom'
      - 'POSTGRES_PASSWORD=12345678'
    volumes:
      - './volumes/ecom/postgres:/var/lib/postgresql/data'
